Repository Good-First-Issue-FOSS/MAC_BOT_FOSS, pull requests merged in 2023-06, with the labels that each got.

#12 license upd
  README.md
Labels: bug, enhancement, good first issue

#18 feat: enable linter, add ci
  .eslintrc.json
  .github/ISSUE_TEMPLATE/workflows/node-ci.yml
  .prettierrc.json
  package-lock.json
  package.json
  src/cmd/Auth.ts
  src/cmd/Profile.ts
  src/cmd/Projects.ts
  src/cmd/RequestFeature.ts
  src/cmd/RequestHelp.ts
  src/cmd/RequestIssue.ts
  src/cmd/ping.ts
  src/data/MongoData.ts
  src/interfaces/Command.ts
  src/interfaces/ExtendedClient.ts
  src/setup.ts
  src/utils/loadEnv.ts
Labels: documentation, enhancement, help wanted, question, TS

#19 fix(tools): move workflow file to correct location
  .github/workflows/node-ci.yml
Labels: bug, documentation

#26 pritter
  package.json
Labels: enhancement
